spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/testtms
    username: postgres
    password: 148148
    driver-class-name: org.postgresql.Driver

server:
  port: 8080